apiVersion: v1
kind: Pod
metadata:
   name: trainingdatagenerator
   labels:
    environment: training
    app: trainingdatagen
spec:
   containers:
   - name: trainingdatagen
     image: kingdom36/trainingdatagenerator
     ports:
     - containerPort: 8080
     volumeMounts:
     - name: config
       mountPath: /usr/src/trainingDataGenerator/config.d
       readOnly: true
   volumes:
   - name: config
     configMap:
        name: training-config
        
        
      